### PR TITLE
Part of TARDIS PR (sort of)

### PR DESCRIPTION
**Pull request by DalekCraft2**
See the aforementioned for details.

I managed to change the names of files in this, and I plan to do it for the two main plugins, as well.

This is technically not a TARDIS addon, but I still felt like doing it because it has “TARDIS” in its name. That meaning that I did not notice that it was not an addon until a bit into the editing. Still, I do not care.

why does this even have “tardis” in its name

### CODE REVIEW

**Comment by eccentricdevotion** [comment]
Plugin was made for a TARDIS server, where the only function of their shop was to sell TARDIS things

**Comment by DalekCraft2** [comment]
But is that not the purpose of TARDISShop? This one, TARDISShopDoor, does not even use classes from any TARDIS addon in any way.

**Comment by eccentricdevotion** [comment]
This was made long before the TARDISShop plugin was around and is specific to the server that requested it. It has never been released publicly on Bukkit or Spigot... The name suits the intended purpose.

**Comment by DalekCraft2** [comment]
Does the server still use it, and does it still even exist? If one answer is "no", I can just close this PR and archive the fork.

**Comment by eccentricdevotion** [comment]
The server is no longer running, hence why the plugin hasn't been updated.

**Comment by eccentricdevotion** [comment]
Closing, due to repository archiving

**Pull request closed without merging**
